services:
  db-master:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_network
    ports:
      - "5432:5432"
    volumes:
      - ./init-master.sh:/docker-entrypoint-initdb.d/init-master.sh
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - postgres_master_data:/var/lib/postgresql/data
    command: >
      postgres
      -c wal_level=replica
      -c max_wal_senders=10
      -c max_replication_slots=10
      -c hot_standby=on
      -c wal_keep_size=1GB
    networks:
      - postgres_net

  db-slave1:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_network
      POSTGRES_SERVER_NAME: db-slave1
    ports:
      - "5433:5432"
    volumes:
      - ./init-slave.sh:/docker-entrypoint-initdb.d/init-slave.sh
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - postgres_slave1_data:/var/lib/postgresql/data
    command: >
      postgres
      -c hot_standby=on
    depends_on:
      - db-master
    networks:
      - postgres_net

  db-slave2:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_network
      POSTGRES_SERVER_NAME: db-slave2
    ports:
      - "5434:5432"
    volumes:
      - ./init-slave.sh:/docker-entrypoint-initdb.d/init-slave.sh
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - postgres_slave2_data:/var/lib/postgresql/data
    command: >
      postgres
      -c hot_standby=on
    depends_on:
      - db-master
    networks:
      - postgres_net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - postgres_net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - db-master
      - db-slave1
      - db-slave2
      - redis
    environment:
      - DB_HOST=db-master
      - DB_SLAVE1_HOST=db-slave1
      - DB_SLAVE2_HOST=db-slave2
      - DB_PORT=5432
      - DB_NAME=social_network
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    networks:
      - postgres_net

networks:
  postgres_net:
    driver: bridge

volumes:
  postgres_master_data:
    name: postgres_master_data
  postgres_slave1_data:
    name: postgres_slave1_data
  postgres_slave2_data:
    name: postgres_slave2_data
  redis_data:
    name: redis_data