services:
  # PostgreSQL база данных
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: social_network
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis для кэширования и диалогов
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Dialog Service
  dialog-service:
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile.dialog
    ports:
      - "8002:8002"
    environment:
      # База данных
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/social_network
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: social_network
      DB_USER: postgres
      DB_PASSWORD: postgres
      
      # Redis
      REDIS_URL: redis://redis:6379/1
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 1
      
      # Настройки сервиса
      DIALOG_BACKEND: redis
      LOG_LEVEL: INFO
      DEBUG: "false"
      
      # Events configuration (Iteration 2: RabbitMQ)
      EVENTS_TRANSPORT: rabbitmq
      RABBITMQ_URL: amqp://admin:admin123@rabbitmq:5672/
      COUNTER_SERVICE_URL: http://counter-service:8003
      
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  # Основное монолитное приложение
  monolith:
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile.api
    ports:
      - "8000:9000"
    environment:
      # Настройки базы данных для database.py
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_NAME: "social_network"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      
      # Настройки базы данных для config.py
      DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgres:5432/social_network"
      DATABASE_POOL_SIZE: "10"
      DATABASE_MAX_OVERFLOW: "20"
      
      # Настройки Redis
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_DB: "0"
      
      # Настройки Dialog Service
      DIALOG_SERVICE_URL: "http://dialog-service:8002"
      DIALOG_FALLBACK_ENABLED: "true"
      DIALOG_BACKEND: ${DIALOG_BACKEND:-postgresql}
      
      # Настройки приложения
      LOG_LEVEL: "INFO"
      SECRET_KEY: "your-secret-key-here"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      dialog-service:
        condition: service_healthy
    restart: unless-stopped

  # Nginx для проксирования (опционально)
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - monolith
      - dialog-service
      - counter-service
    restart: unless-stopped

  # Counter Service (DZ-10)
  counter-service:
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile.counter
    ports:
      - "8003:8003"
    environment:
      REDIS_URL: redis://redis:6379/2
      REDIS_DIALOG_URL: redis://redis:6379/1
      LOG_LEVEL: INFO
      EVENTS_TRANSPORT: rabbitmq
      RABBITMQ_URL: amqp://admin:admin123@rabbitmq:5672/
      RECONCILIATION_ENABLED: "true"
      RECONCILIATION_INTERVAL_SEC: 60
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  # RabbitMQ для событий между сервисами
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"     # AMQP port
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  default:
    driver: bridge