version: '3.8'

services:
  db-master:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_network
    ports:
      - "5432:5432"
    volumes:
      - ./init-master-sync.sh:/docker-entrypoint-initdb.d/init-master-sync.sh
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - postgres_master_sync_data:/var/lib/postgresql/data
    command: >
      postgres
      -c wal_level=replica
      -c max_wal_senders=10
      -c max_replication_slots=10
      -c hot_standby=on
      -c synchronous_standby_names='ANY 2 (slave1, slave2, slave3)'
      -c synchronous_commit=on
    networks:
      - postgres_net

  db-slave1:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_network
      HOSTNAME: slave1
    ports:
      - "5433:5432"
    volumes:
      - ./init-slave-sync.sh:/docker-entrypoint-initdb.d/init-slave-sync.sh
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - postgres_slave1_sync_data:/var/lib/postgresql/data
    command: >
      postgres
      -c hot_standby=on
    depends_on:
      - db-master
    networks:
      - postgres_net

  db-slave2:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_network
      HOSTNAME: slave2
    ports:
      - "5434:5432"
    volumes:
      - ./init-slave-sync.sh:/docker-entrypoint-initdb.d/init-slave-sync.sh
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - postgres_slave2_sync_data:/var/lib/postgresql/data
    command: >
      postgres
      -c hot_standby=on
    depends_on:
      - db-master
    networks:
      - postgres_net

  db-slave3:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_network
      HOSTNAME: slave3
    ports:
      - "5435:5432"
    volumes:
      - ./init-slave-sync.sh:/docker-entrypoint-initdb.d/init-slave-sync.sh
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - postgres_slave3_sync_data:/var/lib/postgresql/data
    command: >
      postgres
      -c hot_standby=on
    depends_on:
      - db-master
    networks:
      - postgres_net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - db-master
      - db-slave1
      - db-slave2
      - db-slave3
    environment:
      - DB_HOST=db-master
      - DB_PORT=5432
      - DB_NAME=social_network
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    networks:
      - postgres_net

networks:
  postgres_net:
    driver: bridge

volumes:
  postgres_master_sync_data:
    name: postgres_master_sync_data
  postgres_slave1_sync_data:
    name: postgres_slave1_sync_data
  postgres_slave2_sync_data:
    name: postgres_slave2_sync_data
  postgres_slave3_sync_data:
    name: postgres_slave3_sync_data
