version: '3'

services:
  db-master:
    image: postgres:14
    container_name: db-master
    hostname: db-master
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=social_network
    volumes:
      - ./pg_master_init.sh:/docker-entrypoint-initdb.d/pg_master_init.sh
    ports:
      - "5432:5432"
    networks:
      - postgres_net

  db-slave1:
    image: postgres:14
    container_name: db-slave1
    hostname: db-slave1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=social_network
    volumes:
      - ./pg_slave_init.sh:/docker-entrypoint-initdb.d/pg_slave_init.sh
    ports:
      - "5433:5432"
    depends_on:
      - db-master
    networks:
      - postgres_net

  db-slave2:
    image: postgres:14
    container_name: db-slave2
    hostname: db-slave2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=social_network
    volumes:
      - ./pg_slave_init.sh:/docker-entrypoint-initdb.d/pg_slave_init.sh
    ports:
      - "5434:5432"
    depends_on:
      - db-master
    networks:
      - postgres_net

  db-slave3:
    image: postgres:14
    container_name: db-slave3
    hostname: db-slave3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=social_network
    volumes:
      - ./pg_slave_init.sh:/docker-entrypoint-initdb.d/pg_slave_init.sh
    ports:
      - "5435:5432"
    depends_on:
      - db-master
    networks:
      - postgres_net

  app:
    image: postgres:14
    container_name: app
    hostname: app
    command: ["sleep", "infinity"]
    depends_on:
      - db-master
      - db-slave1
      - db-slave2
      - db-slave3
    networks:
      - postgres_net

networks:
  postgres_net:
    driver: bridge
